#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require_relative '../lib/fusuma/plugin/application_matcher/bamf.rb'
require_relative '../lib/fusuma/plugin/application_matcher/version.rb'

option = {}
opt = OptionParser.new

opt.on('-l', '--list-applications',
       'List applications') do |v|
  option[:list] = v
end

opt.on('--version', 'Show version') do |v|
  option[:version] = v
end

opt.parse!(ARGV)

if option[:list]
  matcher = Fusuma::Plugin::ApplicationMatcher::Bamf::Matcher.new(DBus.session_bus)
  puts matcher.running_applications.map(&:name)
  return
end

if option[:version]
  puts Fusuma::Plugin::ApplicationMatcher::VERSION
  return
end

matcher = Fusuma::Plugin::ApplicationMatcher::Bamf::Matcher.new(DBus.session_bus)
puts matcher.active_application.name
